footypicks/footypicks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include(('game.urls', 'game'), namespace='game')),
    path('admin/', admin.site.urls),
    path('players/', include('players.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns
else:
    urlpatterns += staticfiles_urlpatterns()

footypicks/game/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('minileague/<int:pk>/', views.MiniLeagueDetail.as_view(), name='minileague_detail'),
    path('minileague/<int:pk>/join/', views.MiniLeagueJoin.as_view(), name='minileague_join'),
    path('minileague/<int:pk>/invite/', views.MiniLeagueInvite.as_view(), name='minileague_invite'),
    path('minileague/<int:pk>/edit/', views.MiniLeagueEdit.as_view(), name='minileague_edit'),
    path('minileague/<int:pk>/end/', views.MiniLeagueEnd.as_view(), name='minileague_end'),
    path('minileague/<int:pk>/games/', views.GameweekList.as_view(), name='gameweek_list'),
    path('profile/<int:pk>/', views.PlayerDetail.as_view(), name='player_detail'),
    path('profile/<int:pk>/transactions/', views.PlayerTransactionList.as_view(), name='player_transactions_by_id'),
    path('profile/edit_details/', views.PlayerEdit.as_view(), name='player_edit'),
    path('profile/transactions/', views.PlayerTransactionList.as_view(), name='player_transactions'),
    path('profile/new_transaction/', views.PlayerTransactionCreate.as_view(), name='player_transaction_new'),
    path('profile/edit_transaction/<int:pk>/', views.PlayerTransactionEdit.as_view(), name='player_transaction_edit'),
    path('game/<int:pk>/', views.GameweekDetail.as_view(), name='game_detail'),
    path('game/<int:pk>/edit/', views.GameweekEdit.as_view(), name='game_edit'),
    path('game/create/', views.GameweekCreate.as_view(), name='game_create'),
    path('game/<int:pk>/end/', views.GameweekEnd.as_view(), name='game_end'),
    path('game/<int:pk>/predict/', views.EditPredictions.as_view(), name='game_predict'),
    path('leaderboard/<int:pk>/', views.GameweekLeaderboardDetail.as_view(), name='leaderboard_detail'),
    path('leaderboard/<int:pk>/edit/', views.GameweekLeaderboardEdit.as_view(), name='leaderboard_edit'),
    path('leaderboard/create/', views.GameweekLeaderboardCreate.as_view(), name='leaderboard_create'),
    path('leaderboard/<int:pk>/end/', views.GameweekLeaderboardEnd.as_view(), name='leaderboard_end'),
    path("signup/", views.PlayerSignUp.as_view(), name="signup"),
    path("about/", views.AboutView.as_view(), name="about")
]

footypicks/game/views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView, TemplateView, View, RedirectView
from django.shortcuts import get_object_or_404, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import FormMixin
from .forms import *
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from players.models import Player, Transaction
from players.forms import TransactionCreateForm
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



# Custom Template Views (DRY)
class CreateTemplate(CreateView):
    template_name = 'game/pages/simple_form.html'
    fields = '__all__'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        context['subtitle'] = 'Create'
        return context


class UpdateTemplate(UpdateView):
    template_name = 'game/pages/simple_form.html'
    fields = '__all__'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit'
        context['subtitle'] = 'Edit'
        return context


# Home page View. Only seen by anons
class HomeView(TemplateView):
    template_name = 'game/pages/home.html'

    def get(self, request, *args, **kwargs):
        # Redirect user to their profile page if logged in
        if self.request.user.is_authenticated:
            #league_id = self.request.user.player.minileague_set.all().order_by('-pk')[0].id
            return redirect('game:player_detail', pk=request.user.player.id)
        else: # Redirect to login
            #return super().get(request, *args, **kwargs)
            return redirect('login')

class AboutView(TemplateView):
    template_name = 'game/pages/about.html'


# Mini League Views
class MiniLeagueDetail(DetailView):
    '''
    Overall View for a Mini-League.
    '''

    model = MiniLeague
    template_name = 'game/pages/minileague_detail.html'
    context_object_name = 'league'

    def get_object(self):
        if 'pk' not in self.kwargs or self.kwargs['pk'] == 0:
            ml = MiniLeague.objects.get(play_link=True)
            self.kwargs['pk'] = ml.id
            return ml
        return super(MiniLeagueDetail, self).get_object()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # List of leaderboards for the ML
        context['leaderboards'] = self.object.get_aggregated_gameweeks()
        # context['players'] = self.object.players.all().order_by('user__username')
        # Gameweek queryset
        games = self.object.get_gameweeks()
        # Provide context with all games, previous 3 games and, upcoming 3 games
        context['games'] = games
        context['prev_games'] = games.filter(end_date__lte=datetime.now().date()).order_by('-end_date')[:3]
        context['next_games'] = games.filter(start_date__gte=datetime.now().date())[:3]
        context['live_games'] = games.filter(start_date__lte=datetime.now().date(),
                                             end_date__gte=datetime.now().date())[:3]
        # Score Structure of Mini-League
        context['score'] = self.object.score_structure.get_fields()
        # If user is logged in provide additional context
        if self.request.user.is_authenticated:
            current_player = self.request.user.player
            # These determine if user can edit the ML
            context['player_is_owner'] = self.object.player_is_owner(current_player.id)
            context['player_is_member'] = self.object.player_is_member(current_player.id)
        # Try to provide Primary AG Leaderboard. Wrapped in a Try to avoid errors if one doesn't exist.
        try:
            context['primary_leaderboard'] = self.object.leaderboards.get(primary_ag=True).leaderboard()
        except:
            pass
        context['players'] = self.object.new_players()
        return context


class MiniLeagueJoin(LoginRequiredMixin, FormMixin, DetailView):
    '''
    Simple form for new players to join an existing ML.
    '''

    model = MiniLeague
    template_name = 'game/pages/simple_form.html'
    context_object_name = 'league'
    form_class = JoinLeagueForm
    success_url = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Join League'
        context['subtitle'] = self.object.name
        return context

    def get(self, request, *args, **kwargs):
        obj = self.model.objects.get(pk=kwargs['pk'])
        # Block players joining a dead League
        if any(ele in DEAD_STATUSES for ele in obj.status):
            messages.warning(self.request, "MiniLeague closed to new members")
            return redirect('game:minileague_detail', kwargs['pk'])
        return super().get(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        # Prefill password field if URL parameter exists
        initial['league_password'] = self.request.GET.get('password', None)
        return initial


    def post(self, request, *args, **kwargs):
        post = request.POST
        print(post)
        attempt_password = post['league_password']
        obj = self.model.objects.get(pk=kwargs['pk'])
        correct_password = obj.password
        print("P", correct_password)
        # Checks password provided.

        if obj.players.filter(pk=request.user.player.id).count() == 1: # Player is already a member
            messages.info(self.request, "Already a member of the Mini-league")
            return redirect('game:minileague_detail', kwargs['pk'])
        elif attempt_password == correct_password: # Correct password provided
            obj.players.add(request.user.player)
            obj.save()
            messages.success(self.request, "Successfully joined Mini-League")
            return redirect('game:minileague_detail', kwargs['pk'])
        else: # Incorrect password provided
            messages.error(self.request, "Incorrect password provided")
            return redirect('game:minileague_join', kwargs['pk'])

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('game:minileague_detail')


class MiniLeagueInvite(TemplateView):
    '''
    Simple redirect back to MiniLeagueDetail page providing a message with the invite link
    '''
    template_name = 'game/pages/minileague_detail.html'

    def get(self, request, *args, **kwargs):
        league_id = kwargs['pk']
        league = MiniLeague.objects.get(pk=league_id)
        # Only a League owner can request the password for a League
        if self.request.user.is_authenticated and league.player_is_owner(self.request.user.player.id):
            url = request.build_absolute_uri(reverse('game:minileague_join', kwargs={'pk': league_id}))
            url += f"?password={league.password}"
            # Provide the invite link as a message
            messages.info(request, f" Share Link: <a href='{url}'>{url}</a>")
        else:
            # User isn't authorised to ask for a link
            messages.warning(request, f"Only the League Owner can see the League Password")
        return redirect('game:minileague_detail', pk=league_id)


class MiniLeagueEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateTemplate):
    '''
    Simple form to edit some of the Mini League values
    '''

    model = MiniLeague
    form_class = MiniLeagueEditForm
    fields = None

    def test_func(self):
        # Only League Owners can access this page
        return self.get_object().player_is_owner(self.request.user.player.id)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit League'
        context['subtitle'] = self.object.name

        # Generates tables of score structures for easy reference

        context['additional_html'] = "<h3>Score Structures</h3>"
        context['additional_html'] += "<div class='row'>"
        for s in Score.objects.all():
            context['additional_html'] += f"<div class'col-auto'><h4>{s.name}</h4><table>"

            for k, v in s.get_fields():
                context['additional_html'] += f"<tr><th>{k.replace('_', ' ').upper()}</th><td>{v}</td></tr>"
            context['additional_html'] += "</table></div>"
        context['additional_html'] += "</div>"
        return context


class MiniLeagueEnd(LoginRequiredMixin, UserPassesTestMixin, UpdateTemplate):
    pass

# Game Views
class GameweekDetail(DetailView):
    '''
    Basic view of a Gameweek
    '''

    model = Gameweek
    context_object_name = 'game'
    template_name = 'game/pages/gameweek_detail.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # refresh the Gameweek
        self.object.refresh_game()
        # Score structure
        context['score'] = self.object.mini_league.score_structure.get_fields()
        # Gameweek list queryset
        games = self.object.mini_league.get_gameweeks()
        # Provide the context with all games, recent 3 and next 3
        context['games'] = games
        context['prev_games'] = games.filter(end_date__lte=datetime.now()).order_by('-end_date')[:3]
        context['next_games'] = games.filter(start_date__gte=datetime.now())[:3]
        # Provide context with list of leaderboards
        context['leaderboards'] = self.object.mini_league.get_aggregated_gameweeks()
        # Prize pool table
        context['prize_pool'] = self.object.prize_table()
        # Provide additional context if user is logged in

footypicks/game/templates/game/pages/end_game.html
{% extends 'game/base.html' %}
{% load static %}
{% block title %}Game Detail{% endblock %}
{% block content %}

<div class="container-fluid main-content-area" xmlns="http://www.w3.org/1999/html">
    <div class="row m-1">
        <div class="btn-group">
            <div class="col-auto">
                <a href="{% url 'game:minileague_detail' pk=game.mini_league.id %}" class="button btn-default read-more">Back to League</a>
            </div>
            {% if can_predict %}
            <div class="col-auto">
                <a href="{% url 'game:game_predict' pk=game.pk %}" class="button btn-default read-more">Predict</a>
            </div>
            {% endif %}
            {% if player_is_owner %}
            <div class="col-auto">
                <a href="{% url 'game:game_edit' pk=game.pk %}" class="button btn-default read-more">Edit Game</a>
            </div>
            <div class="col-auto">
                <a href="{% url 'game:game_edit' pk=game.pk %}" class="button btn-default read-more">End Game</a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="row m-1">
        <div class="col post-title-content">
            <h1 class="entry-title">{{ game.mini_league.name }}</h1>
        </div>
    </div>
    {% include 'game/partials/messages.html' %}
    <div class="row m-1">
        <div class="col-lg-2 col-sm-3">
            <div class="row well">
                <div class="col">
                    {% include 'game/partials/prizes.html' with prize_table=game.prize_table %}
                    {% include 'game/partials/side_menu.html' %}
                </div>
            </div>
        </div>
        <div class="col-lg-10 col-sm">
            <div class="row post-inner-content">
                <div class="row">
                    <div class="col-6">
                        <h2 class="alignleft">{{ game }}</h2>
                    </div>
                    <div class="col-6">
                        <h3 class="alignright">{{ game.get_status_display }}</h3>
                    </div>
                    <div class="col-6">
                        <h5 class="alignleft"><i class="fa-solid fa-fw fa-calendar-days"></i>{{ game.start_date|date:"jS M Y" }} to {{ game.end_date|date:"jS M Y" }}</h5>
                    </div>
                    <div class="col-6">
                        <h5 class="alignright">Last update: {{ game.last_update }}</h5>
                    </div>
                </div>
                <div id="grad-thin"></div>
                <div class="col-lg-5 col-sm-6">
                    <h5>Fixtures</h5>
                    {% include 'game/partials/fixtures_table.html' with fixtures=game.fixtures.all %}
                </div>
                <div class="col-lg-4 col-sm-6">
                    {% if user.is_authenticated or player %}
                    <h5>{{ player }}'s Picks</h5>
                    {% else %}
                    <h5>Picks</h5>
                    {% endif %}
                    {% if player_picks %}
                    {% include 'game/partials/player_predictions.html' with player_picks=player_picks %}
                    {% else %}
                    No Picks submitted
                    {% endif %}
                </div>
                <div class="col-lg-3 col-sm-9">
                    <h5>Leaderboard</h5>
                    {% include 'game/partials/leaderboard.html' with leaderboard=leaderboard %}
                </div>

                <!--<div class="col-lg-6 col-sm">
                    <h5>Prediction Matrix</h5>
                    {% include 'game/partials/pick_matrix.html' %}
                </div> -->
            </div>
        </div>
        <!--<div class="col-lg-2 col-sm-3 border">
            <h5>Scoring</h5>
            {% include 'game/partials/score_structure.html' with score=score %}
            <h5>Prize Pool</h5>
            POOL HERE
        </div>-->

    </div>
    <!--<div class="row">
        <div class="col-4 col-sm border">
            PICKS MATRIX GOES HERE
        </div>
        <div class="col-4 col-sm border">
            CHANCE OF WINNING CALCULATION GOES HERE
        </div>
    </div>-->


</div>
{% endblock %}

footypicks/game/templates/game/pages/gameweek_detail.html
{% extends 'game/base.html' %}
{% load static %}
{% block title %}Game Detail{% endblock %}
{% block content %}

<div class="container-fluid main-content-area" xmlns="http://www.w3.org/1999/html">
    <div class="row m-1">
        <div class="btn-group">
            <div class="col-auto">
                <a href="{% url 'game:minileague_detail' pk=game.mini_league.id %}"
                   class="button btn-default read-more">
                    <i class="fa-solid fa-arrow-left"></i> League
                </a>
            </div>
            {% if can_predict %}
            <div class="col-auto">
                <a href="{% url 'game:game_predict' pk=game.pk %}" class="button btn-default read-more">
                    <i class="fa-solid fa-wand-sparkles"></i> Predict
                </a>
            </div>
            {% endif %}
            {% if player_is_owner %}
            <div class="col-auto">
                <a href="{% url 'game:game_edit' pk=game.pk %}" class="button btn-default read-more">
                    <i class="fa-solid fa-pen-to-square"></i> Edit</a>
            </div>

            <div class="col-auto">
                <a href="{% url 'game:game_end' pk=game.pk %}" class="button btn-default read-more">
                    <i class="fa-solid fa-flag-checkered"></i> End
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="row m-1">
        <div class="col post-title-content">
            <h1 class="entry-title">{{ game.mini_league.name }}</h1>
        </div>
    </div>
    {% include 'game/partials/messages.html' %}
    <div class="row m-1">
        <div class="col-lg-10 col-sm-12 col-md-12">
            <div class="row post-inner-content">
                <div class="row">
                    <div class="col-12">
                        <h2 class="alignleft"><i class="fa-solid fa-dice"></i> {{ game }}</h2>
                    </div>
                    <!--<div class="col-6">
                        <h3 class="alignright">{{ game.get_status_display }}</h3>
                    </div>-->
                    <p>
                    <i class="fa-solid fa-futbol fa-fw"></i> Check out Player performance in the Game below
                    <i class="fa-solid fa-futbol fa-fw"></i> Go ahead and make your predictions above
                    <i class="fa-solid fa-futbol fa-fw"></i> Come back after the Game has finished to see how you got on
                    <i class="fa-solid fa-futbol fa-fw"></i>
                    </p>
                    <div class="col-lg-6 col-md-12 col-sm-12">
                        <h5 class="alignleft">
                            Last update: <abbr title="{{ game.last_update }}">
                            {{ game.last_update|timesince }}</abbr> ago
                        </h5>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12">
                        <h5 id="content-desktop" class="alignright"><i class="fa-solid fa-fw fa-calendar-days"></i>
                            {{ game.start_date|date:"jS M Y" }} to {{ game.end_date|date:"jS M Y" }}
                        </h5>
                        <h5 id="content-mobile" class="alignleft"><i class="fa-solid fa-fw fa-calendar-days"></i>
                            {{ game.start_date|date:"d/m/Y" }} to {{ game.end_date|date:"d/m/Y" }}
                        </h5>
                    </div>
                </div>
                <div id="grad-thin"></div>
                <div class="col-lg-5 col-sm-6 col-md-6">
                    <h5><i class="fa-solid fa-futbol"></i> Fixtures</h5>
                    {% include 'game/partials/fixtures_table.html' with fixtures=game.fixtures.all %}
                    <small><i class="fa-solid fa-circle-info"></i>
                        The fixtures everyone's making their Predictions on. Click on
                        <span class="fake-button"><i class="fa-solid fa-wand-sparkles"></i> Predict</span> above to make yours.
                    </small>
                </div>
                <div class="col-lg-4 col-sm-6 col-md-6">
                    {% if user.is_authenticated or player %}
                    <h5><i class="fa-solid fa-wand-sparkles"></i>
                        {{ player }}'s Picks
                    </h5>
                    {% else %}
                    <h5>Picks</h5>
                    {% endif %}
                    {% if player_picks %}
                    {% include 'game/partials/player_predictions.html' with player_picks=player_picks %}
                    {% else %}
                    No Picks submitted
                    {% endif %}
                    <small><i class="fa-solid fa-circle-info"></i>
                        See how this Player's Picks have performed in the Game. Click a name in the Leaderboard to
                        change Player.
                    </small>
                </div>
                <div class="col-lg-3 col-sm-12 com-md-12">
                    <h5><i class="fa-solid fa-ranking-star"></i> Game Leaderboard</h5>
                    {% include 'game/partials/leaderboard.html' with leaderboard=leaderboard %}
                    <small>
                        <i class="fa-solid fa-circle-info"></i>
                        Click on a players name to see their Picks for this Game
                    </small>
                </div>

                <!--<div class="col-lg-6 col-sm">
                    <h5>Prediction Matrix</h5>
                    {% include 'game/partials/pick_matrix.html' %}
                </div> -->
            </div>
        </div>
        <div class="col-lg-2 col-sm-12">
            <div class="row well">
                <div class="col">
                    {% include 'game/partials/prizes.html' with prize_table=game.prize_table %}
                    <small><i class="fa-solid fa-circle-info"></i>
                        Accumulated Prize pool for this Game and the payout.
                        See the About page for a detailed explanation.
                    </small>
                    <hr class="title-line">
                    {% include 'game/partials/side_menu.html' %}
                </div>
            </div>
        </div>
        <!--<div class="col-lg-2 col-sm-3 border">
            <h5>Scoring</h5>
            {% include 'game/partials/score_structure.html' with score=score %}
            <h5>Prize Pool</h5>
            POOL HERE
        </div>-->

    </div>
    <!--<div class="row">
        <div class="col-4 col-sm border">
            PICKS MATRIX GOES HERE
        </div>
        <div class="col-4 col-sm border">
            CHANCE OF WINNING CALCULATION GOES HERE
        </div>
    </div>-->


</div>
{% endblock %}

footypicks/game/templates/game/pages/home.html
{% extends "game/base.html" %}
{% load static %}

{% block content %}
<div>
    <div id="grad-reverse"></div>
    <div class="image">
          <div class="overlay">
          </div>
        </div>
    <div id="grad"></div>
</div>
<div class="container main-content-area">
    <div class="row m-1 post-inner-content">
        <div class="col-12">
            {% if user.is_authenticated %}
            <h4>Your Leagues</h4>
            {% include 'game/partials/leagues_list.html' %}
            {% else %}
            <a class="btn btn-default " href="{% url 'game:signup' %}">Sign up</a>
            {% endif %}
        </div>
        <div class="col-lg-6 col-sm border">
            <h4>Recent Fixtures</h4>
        </div>
        <div class="col-lg-6 col-sm border">
            <h4>Upcoming Fixtures</h4>
        </div>
    </div>
</div>
{% endblock %}

footypicks/game/templates/game/pages/minileague_detail.html
{% extends 'game/base.html' %}
{% load static %}
{% block title %}Mini League{% endblock %}
{% block content %}

<div class="container-fluid main-content-area">
    <div class="row m-1">
        {% if player_is_owner %}
        <div class="btn-group">
            <div class="col-auto pr-1">
                <a href="{% url 'game:minileague_invite' pk=league.pk %}" class="button btn-default read-more">
                    <i class="fa-solid fa-share-nodes"></i> Invite
                </a>
            </div>
            <div class="col-auto pr-1">
                <a href="{% url 'game:minileague_edit' pk=league.pk %}" class="button btn-default read-more">
                    <i class="fa-solid fa-pen-to-square"></i> Edit
                </a>
            </div>
            <div class="col-auto pr-1">
                <a href="{% url 'game:leaderboard_create' %}?minileague={{ league.id }}"
                   class="button btn-default read-more">
                    <i class="fa-solid fa-plus"></i> Leaderboard
                </a>
            </div>
            <div class="col-auto pr-1">
                <a href="{% url 'game:game_create'%}?minileague={{ league.id }}"
                   class="button btn-default read-more">
                    <i class="fa-solid fa-plus"></i> Game
                </a>
            </div>
        </div>
        {% endif %}
        {% if not player_is_member %}
        <div class="col-auto">
            <a href="{% url 'game:minileague_join' pk=league.pk %}" class="button btn-default read-more">
                <i class="fa-solid fa-user-plus"></i>Join
            </a>
        </div>
        {% endif %}
    </div>
    <div class="row m-1">
        <div class="col post-title-content">
            <h1 class="entry-title">{{ league.name }}</h1>
        </div>
    </div>
    {% include 'game/partials/messages.html' %}
    <div class="row m-1">
        <div class="col-lg-10 col-sm col-md-8">
            <div class="row post-inner-content">
                <p>
                    <i class="fa-solid fa-futbol fa-fw"></i> Check out Player performance in Games and Leaderboards below
                    <i class="fa-solid fa-futbol fa-fw"></i> Go ahead and make your predictions in the next Game before
                    the Start Date
                    <i class="fa-solid fa-futbol fa-fw"></i> Come back after a Game has ended to see how your Picks got on
                    <i class="fa-solid fa-futbol fa-fw"></i> Visit a Leaderboard to see how you got on over a set period
                    of Games
                    <i class="fa-solid fa-futbol fa-fw"></i>
                    <div id="grad-thin"></div>
                </p>

                <div class="col-lg-3 col-sm">
                    <h5><i class="fa-solid fa-ranking-star"></i> Leaderboards</h5>
                    {% include 'game/partials/leaderboard_list.html' with leaderboards=leaderboards %}
                    <small><i class="fa-solid fa-circle-info"></i>
                        Click on a leaderboard above to view aggregated games. Prizes awarded to top players.
                    </small>
                    <div id="grad-thin"></div>
                </div>
                <div class="col-lg-3 col-sm">
                    <h5><i class="fa-solid fa-dice"></i> Games</h5>
                    {% if live_games %}
                    {% include 'game/partials/gameweeks_list.html' with games=live_games heading="Live" %}
                    {% endif %}
                    {% include 'game/partials/gameweeks_list.html' with games=prev_games heading="Previous" %}
                    <small><i class="fa-solid fa-circle-info"></i> Click on a Game to see results.</small>
                    {% include 'game/partials/gameweeks_list.html' with games=next_games heading="Next" %}
                    <small>
                        <i class="fa-solid fa-circle-info">
                        </i> Click on a Game to make your Predictions and see upcoming fixtures
                    </small><br>
                    <a href="{% url 'game:gameweek_list' pk=league.id %}">All Games</a>
                    <div id="grad-thin"></div>
                </div>
                <div class="col-lg-6 col-sm p-1">
                    <h5><i class="fa-solid fa-ranking-star"></i> {{ league.primary_leaderboard.name }} Leaderboard</h5>
                    {% include 'game/partials/expanded_leaderboard.html' with leaderboard=primary_leaderboard %}
                    <small><i class="fa-solid fa-circle-info"></i>
                        See how you're getting on in the Annual Leaderboard.
                    </small>
                    <div id="grad-thin"></div>
                    <!--<h5><i class="fa-solid fa-user-tie"></i> New Players</h5>
                    {% include 'game/partials/league_members_list.html' %}-->
                </div>
                {% if player_is_owner %}
                <div class="col-lg-6 col-sm-12 p-2">
                    <h5>Player Balances</h5>
                    {% include 'game/partials/gameweek_player_balances.html' %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-2 col-sm col-md-4">
            <div class="row well">
                <div class="col-auto">
                    <h5><i class="fa-solid fa-sterling-sign"></i> Entry Cost</h5>
                    <table class="table table-sm small">
                        <tr>
                            <th style="width:70%;">Per Game</th>
                            <td>&pound;{{ league.gameweek_fee }}</td>
                        </tr>
                    </table>
                    <small><i class="fa-solid fa-circle-info"></i>
                        The cost per Game to play in this Mini-League. Fees are deducted from your Balance when you
                        submit your Picks. See your Profile for your current Balance and to make a topup.
                    </small>
                    <hr class="title-line">
                    {% include 'game/partials/side_menu.html' %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

footypicks/game/templates/game/pages/simple_form.html
{% extends 'game/base.html' %}
{% load static %}
{% block title %}Player Profile{% endblock %}
{% block content %}

<div class="container main-content-area">
    <div class="row m-1">
        <div class="col post-title-content">
            <h1 class="entry-title">{{ title }}</h1>
        </div>
    </div>
    {% include 'game/partials/messages.html' %}
    <div class="row m-1 post-inner-content">
        <h2>{{ subtitle }}</h2>
        <div id="grad-thin"></div>
        {% include 'game/partials/simple_form.html' %}
        <div id="grad-thin"></div>

        {{ additional_html|safe }}

    </div>
</div>

{% endblock %}