footypicks/footypicks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include(('game.urls', 'game'), namespace='game')),
    path('admin/', admin.site.urls),
    path('players/', include('players.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns
else:
    urlpatterns += staticfiles_urlpatterns()

footypicks/game/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('minileague/<int:pk>/', views.MiniLeagueDetail.as_view(), name='minileague_detail'),
    path('minileague/<int:pk>/join/', views.MiniLeagueJoin.as_view(), name='minileague_join'),
    path('minileague/<int:pk>/invite/', views.MiniLeagueInvite.as_view(), name='minileague_invite'),
    path('minileague/<int:pk>/edit/', views.MiniLeagueEdit.as_view(), name='minileague_edit'),
    path('minileague/<int:pk>/end/', views.MiniLeagueEnd.as_view(), name='minileague_end'),
    path('minileague/<int:pk>/games/', views.GameweekList.as_view(), name='gameweek_list'),
    path('profile/<int:pk>/', views.PlayerDetail.as_view(), name='player_detail'),
    path('profile/<int:pk>/transactions/', views.PlayerTransactionList.as_view(), name='player_transactions_by_id'),
    path('profile/edit_details/', views.PlayerEdit.as_view(), name='player_edit'),
    path('profile/transactions/', views.PlayerTransactionList.as_view(), name='player_transactions'),
    path('profile/new_transaction/', views.PlayerTransactionCreate.as_view(), name='player_transaction_new'),
    path('profile/edit_transaction/<int:pk>/', views.PlayerTransactionEdit.as_view(), name='player_transaction_edit'),
    path('game/<int:pk>/', views.GameweekDetail.as_view(), name='game_detail'),
    path('game/<int:pk>/edit/', views.GameweekEdit.as_view(), name='game_edit'),
    path('game/create/', views.GameweekCreate.as_view(), name='game_create'),
    path('game/<int:pk>/end/', views.GameweekEnd.as_view(), name='game_end'),
    path('game/<int:pk>/predict/', views.EditPredictions.as_view(), name='game_predict'),
    path('leaderboard/<int:pk>/', views.GameweekLeaderboardDetail.as_view(), name='leaderboard_detail'),
    path('leaderboard/<int:pk>/edit/', views.GameweekLeaderboardEdit.as_view(), name='leaderboard_edit'),
    path('leaderboard/create/', views.GameweekLeaderboardCreate.as_view(), name='leaderboard_create'),
    path('leaderboard/<int:pk>/end/', views.GameweekLeaderboardEnd.as_view(), name='leaderboard_end'),
    path("signup/", views.PlayerSignUp.as_view(), name="signup"),
    path("about/", views.AboutView.as_view(), name="about")
]

footypicks/game/views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView, TemplateView, View, RedirectView
from django.shortcuts import get_object_or_404, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import FormMixin
from .forms import *
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from players.models import Player, Transaction
from players.forms import TransactionCreateForm
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



# Custom Template Views (DRY)
class CreateTemplate(CreateView):
    template_name = 'game/pages/simple_form.html'
    fields = '__all__'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        context['subtitle'] = 'Create'
        return context


class UpdateTemplate(UpdateView):
    template_name = 'game/pages/simple_form.html'
    fields = '__all__'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit'
        context['subtitle'] = 'Edit'
        return context


# Home page View. Only seen by anons
class HomeView(TemplateView):
    template_name = 'game/pages/home.html'

    def get(self, request, *args, **kwargs):
        # Redirect user to their profile page if logged in
        if self.request.user.is_authenticated:
            #league_id = self.request.user.player.minileague_set.all().order_by('-pk')[0].id
            return redirect('game:player_detail', pk=request.user.player.id)
        else: # Redirect to login
            #return super().get(request, *args, **kwargs)
            return redirect('login')

class AboutView(TemplateView):
    template_name = 'game/pages/about.html'


# Mini League Views
class MiniLeagueDetail(DetailView):
    '''
    Overall View for a Mini-League.
    '''

    model = MiniLeague
    template_name = 'game/pages/minileague_detail.html'
    context_object_name = 'league'

    def get_object(self):
        if 'pk' not in self.kwargs or self.kwargs['pk'] == 0:
            ml = MiniLeague.objects.get(play_link=True)
            self.kwargs['pk'] = ml.id
            return ml
        return super(MiniLeagueDetail, self).get_object()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # List of leaderboards for the ML
        context['leaderboards'] = self.object.get_aggregated_gameweeks()
        # context['players'] = self.object.players.all().order_by('user__username')
        # Gameweek queryset
        games = self.object.get_gameweeks()
        # Provide context with all games, previous 3 games and, upcoming 3 games
        context['games'] = games
        context['prev_games'] = games.filter(end_date__lte=datetime.now().date()).order_by('-end_date')[:3]
        context['next_games'] = games.filter(start_date__gte=datetime.now().date())[:3]
        context['live_games'] = games.filter(start_date__lte=datetime.now().date(),
                                             end_date__gte=datetime.now().date())[:3]
        # Score Structure of Mini-League
        context['score'] = self.object.score_structure.get_fields()
        # If user is logged in provide additional context
        if self.request.user.is_authenticated:
            current_player = self.request.user.player
            # These determine if user can edit the ML
            context['player_is_owner'] = self.object.player_is_owner(current_player.id)
            context['player_is_member'] = self.object.player_is_member(current_player.id)
        # Try to provide Primary AG Leaderboard. Wrapped in a Try to avoid errors if one doesn't exist.
        try:
            context['primary_leaderboard'] = self.object.leaderboards.get(primary_ag=True).leaderboard()
        except:
            pass
        context['players'] = self.object.new_players()
        return context


class MiniLeagueJoin(LoginRequiredMixin, FormMixin, DetailView):
    '''
    Simple form for new players to join an existing ML.
    '''

    model = MiniLeague
    template_name = 'game/pages/simple_form.html'
    context_object_name = 'league'
    form_class = JoinLeagueForm
    success_url = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Join League'
        context['subtitle'] = self.object.name
        return context

    def get(self, request, *args, **kwargs):
        obj = self.model.objects.get(pk=kwargs['pk'])
        # Block players joining a dead League
        if any(ele in DEAD_STATUSES for ele in obj.status):
            messages.warning(self.request, "MiniLeague closed to new members")
            return redirect('game:minileague_detail', kwargs['pk'])
        return super().get(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        # Prefill password field if URL parameter exists
        initial['league_password'] = self.request.GET.get('password', None)
        return initial


    def post(self, request, *args, **kwargs):
        post = request.POST
        print(post)
        attempt_password = post['league_password']
        obj = self.model.objects.get(pk=kwargs['pk'])
        correct_password = obj.password
        print("P", correct_password)
        # Checks password provided.

        if obj.players.filter(pk=request.user.player.id).count() == 1: # Player is already a member
            messages.info(self.request, "Already a member of the Mini-league")
            return redirect('game:minileague_detail', kwargs['pk'])
        elif attempt_password == correct_password: # Correct password provided
            obj.players.add(request.user.player)
            obj.save()
            messages.success(self.request, "Successfully joined Mini-League")
            return redirect('game:minileague_detail', kwargs['pk'])
        else: # Incorrect password provided
            messages.error(self.request, "Incorrect password provided")
            return redirect('game:minileague_join', kwargs['pk'])

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('game:minileague_detail')


class MiniLeagueInvite(TemplateView):
    '''
    Simple redirect back to MiniLeagueDetail page providing a message with the invite link
    '''
    template_name = 'game/pages/minileague_detail.html'

    def get(self, request, *args, **kwargs):
        league_id = kwargs['pk']
        league = MiniLeague.objects.get(pk=league_id)
        # Only a League owner can request the password for a League
        if self.request.user.is_authenticated and league.player_is_owner(self.request.user.player.id):
            url = request.build_absolute_uri(reverse('game:minileague_join', kwargs={'pk': league_id}))
            url += f"?password={league.password}"
            # Provide the invite link as a message
            messages.info(request, f" Share Link: <a href='{url}'>{url}</a>")
        else:
            # User isn't authorised to ask for a link
            messages.warning(request, f"Only the League Owner can see the League Password")
        return redirect('game:minileague_detail', pk=league_id)


class MiniLeagueEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateTemplate):
    '''
    Simple form to edit some of the Mini League values
    '''

    model = MiniLeague
    form_class = MiniLeagueEditForm
    fields = None

    def test_func(self):
        # Only League Owners can access this page
        return self.get_object().player_is_owner(self.request.user.player.id)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit League'
        context['subtitle'] = self.object.name

        # Generates tables of score structures for easy reference

        context['additional_html'] = "<h3>Score Structures</h3>"
        context['additional_html'] += "<div class='row'>"
        for s in Score.objects.all():
            context['additional_html'] += f"<div class'col-auto'><h4>{s.name}</h4><table>"

            for k, v in s.get_fields():
                context['additional_html'] += f"<tr><th>{k.replace('_', ' ').upper()}</th><td>{v}</td></tr>"
            context['additional_html'] += "</table></div>"
        context['additional_html'] += "</div>"
        return context


class MiniLeagueEnd(LoginRequiredMixin, UserPassesTestMixin, UpdateTemplate):
    pass

# Game Views
class GameweekDetail(DetailView):
    '''
    Basic view of a Gameweek
    '''

    model = Gameweek
    context_object_name = 'game'
    template_name = 'game/pages/gameweek_detail.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # refresh the Gameweek
        self.object.refresh_game()
        # Score structure
        context['score'] = self.object.mini_league.score_structure.get_fields()
        # Gameweek list queryset
        games = self.object.mini_league.get_gameweeks()
        # Provide the context with all games, recent 3 and next 3
        context['games'] = games
        context['prev_games'] = games.filter(end_date__lte=datetime.now()).order_by('-end_date')[:3]
        context['next_games'] = games.filter(start_date__gte=datetime.now())[:3]
        # Provide context with list of leaderboards
        context['leaderboards'] = self.object.mini_league.get_aggregated_gameweeks()
        # Prize pool table
        context['prize_pool'] = self.object.prize_table()
        # Provide additional context if user is logged in

footypicks/game/templates/game/partials/expanded_leaderboard.html
{% load humanize %}
{% load static %}
<table class="table table-sm table-hover w-100">
    <thead>
    <tr class="vertical-middle">
        <th style="width:5%;" class="text-center">
            <span id="content-desktop">Position</span>
            <span id="content-mobile">Pos</span>
        </th>
        <th>
            <span id="content-desktop">Player</span>
            <span id="content-mobile">Player</span>
        </th>
        <th class="text-center">
            <span id="content-desktop">Gameweeks</span>
            <span id="content-mobile">GWs</span>
        </th>
        <th class="text-center">
            <span id="content-desktop">Average</span>
            <span id="content-mobile">Avg</span>
        </th>
        <th class="text-center">
            <span id="content-desktop">Max</span>
            <span id="content-mobile">Max</span>
        </th>
        <th class="text-center">
            <span id="content-desktop">Min</span>
            <span id="content-mobile">Min</span>
        </th>
        <th class="text-center">
            <span id="content-desktop">Points</span>
            <span id="content-mobile">Pts</span>
        </th>
    </tr>
    </thead>
    {% for plr in leaderboard %}
    <tr class="vertical-middle">
        {% if forloop.first %}
        <td class="text-center">
            <i id="content-desktop" class="fa-solid fa-trophy gold fa-xl"></i>
            <i id="content-mobile" class="fa-solid fa-trophy gold fa-xl"></i>
        </td>
        {% else %}
        <td class="text-center">{{ forloop.counter|ordinal }}</td>
        {% endif %}
        <th>
            <!-- {% if plr.thumbnail %}
            <img class="p-1" src="{{ plr.thumbnail.url }}" alt="Profile Picture" width="30px">
            {% else %}
            <img class="p-1" src="{% static 'game/img/default.png' %}" alt="Profile Picture" width="30px">
            {% endif %} -->
            {{ plr.name }}
        </th>
        <td class="text-center">{{ plr.count_gameweeks }}</td>
        <td class="text-center">{{ plr.avg_points|floatformat:2 }}</td>
        <td class="text-center">{{ plr.max_points }}</td>
        <td class="text-center">{{ plr.min_points }}</td>
        <td class="text-center"><h4 class="m-0">{{ plr.sum_points }}</h4></td>
    </tr>
    {% endfor %}
</table>

footypicks/game/templates/game/partials/fixtures_table.html
{% load tz %}
<table class="table table-sm small table-hover">
    <thead>
            <th>
                <span id="content-desktop">Competition</span>
                <span id="content-mobile">Comp</span>
            </th>
            <th colspan="3" class="text-center">
                <span id="content-desktop">Fixture</span>
                <span id="content-mobile">Fix</span>
            </th>
            <th>
                <span id="content-desktop">Kick Off</span>
                <span id="content-mobile">KO</span>
            </th>
            <th class="text-center">
                <span id="content-desktop">Result</span>
                <span id="content-mobile">Res</span>
            </th>
        </span>
    </thead>
    {% for fixture in fixtures %}
    <tr class="vertical-middle">
        <td>
            {% if fixture.competition.thumbnail %}
            <span id="content-desktop"><img src="{{ fixture.competition.thumbnail.url }}" width="30px"></span>
            <span id="content-mobile"><img src="{{ fixture.competition.thumbnail.url }}" width="15px"></span>
            {% endif %}
            <span id="content-desktop">{{ fixture.competition.name }}</span>
        </td>
        <td>
            {% if fixture.home_team.thumbnail %}
            <span id="content-desktop"><img src="{{ fixture.home_team.thumbnail.url }}" width="30px"></span>
            <span id="content-mobile"><img src="{{ fixture.home_team.thumbnail.url }}" width="15px"></span>
            {% endif %}
        </td>
        <th class="text-center">
            <span id="content-desktop">{{ fixture.fixture }}</span>
            <span id="content-mobile">{{ fixture.fix }}</span>
        </th>
        <td>
            {% if fixture.away_team.thumbnail %}
            <span id="content-desktop"><img src="{{ fixture.away_team.thumbnail.url }}" width="30px"></span>
            <span id="content-mobile"><img src="{{ fixture.away_team.thumbnail.url }}" width="15px"></span>
            {% endif %}
        </td>
        <td>
            <span id="content-desktop">{{ fixture.kick_off|localtime|date:"D, jS M Y, P" }}</span>
            <span id="content-mobile">{{ fixture.kick_off|localtime|date:"d/m/Y, P" }}</span>
        </td>
        <td class="text-center"><h4>{{ fixture.final_score }}</h4></td>
    </tr>
    {% endfor %}
</table>

footypicks/game/templates/game/partials/footer.html
{% load static %}
<footer class="footer-section set-bg" data-setbg="">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="fs-logo">
                    <div class="logo">
                        <a href="./index.html"><img src="" alt=""></a>
                    </div>
                    <ul>
                        <li><i class="fa fa-envelope"></i> <a href="mailto:footypicksuk@gmail.com">footypicksuk@gmail.com</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright-option">
            <div class="row">
                <div class="col-lg-12">
                    <div class="co-widget">
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

footypicks/game/templates/game/partials/gameweek_player_balances.html
<table class="table table-sm small table-hover w-100">
    <thead>
      <th>Player</th>
      <th>In</th>
      <th>Out</th>
      <th>Fees</th>
      <th>Prizes</th>
      <th>Balance</th>
    </thead>
    <tbody>
      {% for player in league.players.all %}
      <tr>
          <td><a href="{% url 'game:player_detail' pk=player.id %}">{{ player }}</a></td>
            {% with player.all_transactions as trans %}
            <td>&pound;{{ trans.3|default_if_none:"0" }}</td>
            <td>&pound;{{ trans.4|default_if_none:"0" }}</td>
            <td>&pound;{{ trans.7|default_if_none:"0" }}</td>
            <td>&pound;{{ trans.6|default_if_none:"0" }}</td>
            <td>
                &pound;{{ trans.2|default_if_none:"0" }}
                {% if trans.2 < 0 %}
                !! IN ARREARS !!
                {% endif %}
            </td>
            {% endwith %}
      </tr>
      {% endfor %}
    <tr>
        <td>TOTAL</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>

    </tr>
    </tbody>
</table>

footypicks/game/templates/game/partials/gameweeks_list.html
<table class="table table-sm small table-hover">
    <thead>
    <th style="width:25%;">{{ heading }}</th>
        <th style="width:20%;">Start</th>
        <th style="width:20%;">End</th>
    </thead>
    <tbody>
        {% for game in games %}
        <tr>
            <td>
                <a href="{% url 'game:game_detail' game.id %}">{{ game.name }}</a>
            </td>
            <td>{{ game.start_date|date:"D, jS M Y" }}</td>
            <td>{{ game.end_date|date:"D, jS M Y" }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">
                No Games
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

footypicks/game/templates/game/partials/leaderboard.html
{% load humanize %}
{% load static %}
<table class="table table-sm small table-hover">
    <thead>
    <tr>
        <th style="width:5%;">Pos</th>
        <th class="text-strong">Player</th>
        <th class="text-center">Points</th>
    </tr>
    </thead>
    {% for player in game.leaderboard %}
    <tr class="vertical-middle">
        {% if forloop.first %}
        <td class="text-center">
            <i id="content-desktop" class="fa-solid fa-trophy gold fa-2xl"></i>
            <i id="content-mobile" class="fa-solid fa-trophy gold fa-xl"></i>
        </td>
        {% else %}
        <td class="text-center">{{ forloop.counter|ordinal }}</td>
        {% endif %}
        <th class="font-weight-bold">
            {% if player.player.thumbnail %}
            <img class="p-1" src="{{ player.player.thumbnail.url }}" alt="Profile Picture" width="30px">
            {% else %}
            <img class="p-1" src="{% static 'game/img/default.png' %}" alt="Profile Picture" width="30px">
            {% endif %}
            <a href="{% url 'game:game_detail' pk=game.pk %}?player={{ player.player.id }}">{{ player.player }}</a>
        </th>
        <td class="text-center"><h4 class="m-0">{{ player.points }}</h4></td>
    </tr>
    {% endfor %}
</table>

footypicks/game/templates/game/partials/leaderboard_list.html
{% load my_filters %}
<table class="table table-sm small table-hover w-100">
    <thead>
    </thead>
    <tbody>
        {% if leaderboards %}
        {% for lb in leaderboards %}
        <tr>
            <th style="width:35%;">
                {% if lb|get_class == 'Gameweek' %}
                <!-- <abbr title="Submitted"><i class="fa-solid fa-circle-check"></i></abbr>
                <abbr title="DNP"><i class="fa-solid fa-triangle-exclamation"></i></abbr> -->
                <a href="{% url 'game:game_detail' lb.id %}">
                    <abbr title="{{ lb.name }}">{{ lb.name|truncatechars:11 }}</abbr>
                </a>
                {% else %}
                <a href="{% url 'game:leaderboard_detail' lb.id %}">
                    <abbr title="{{ lb.name }}">{{ lb.name|truncatechars:11 }}</abbr>
                </a>
                {% endif %}
            </th>
            <td><i class="fa-solid fa-fw fa-calendar-days red"></i>{{ lb.start_date|date:"jS M Y" }} - {{ lb.end_date|date:"jS M Y" }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr><td>No games</td></tr>
        {% endif %}
    </tbody>
</table>

footypicks/game/templates/game/partials/league_members_list.html
<table class="table table-sm small table-hover">
    <thead>
    </thead>
    <tbody>
        {% for player in players %}
        <tr>
            <td>{{ player }}</td>
        </tr>
        {% empty %}
        <tr><td>None</td></tr>
        {% endfor %}
    </tbody>
</table>

footypicks/game/templates/game/partials/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible m-0" role="alert">
    <button type="button" class="close button-circle" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message|safe }}
</div>
{% endfor %}

footypicks/game/templates/game/partials/pick_matrix.html
<table class="table table-sm small border">
    <thead>
    <th></th>
    <th>Player A</th>
    <th>Player B</th>
    <th>Player C</th>
    </thead>
    <tbody>
    <tr>
        <th>Game 1 | 2-2</th>
        <td>Pick 1A</td>
        <td>Pick 1B</td>
        <td>Pick 1C</td>
    </tr>
    <tr>
        <th>Game 2 | 2-1</th>
        <td>Pick 2A</td>
        <td>Pick 2B</td>
        <td>Pick 2C</td>
    </tr>
    <tr>
        <th>Game 3 | 1-2</th>
        <td>Pick 3A</td>
        <td>Pick 3B</td>
        <td>Pick 3C</td>
    </tr>
    </tbody>
</table>

footypicks/game/templates/game/partials/side_menu.html
<div class="row">
    <div class="col-lg-12 ">
        <h5><i class="fa-solid fa-calculator"></i> Scoring</h5>
        {% include 'game/partials/score_structure.html' with score=score %}
        <small><i class="fa-solid fa-circle-info"></i>
            Points awarded for accurate Predictions. See the About page for a detailed explanation.
        </small>
    </div>
    <hr class="title-line">
    <div class="col-lg-12 ">
        <h5><i class="fa-solid fa-ranking-star"></i> Leaderboards</h5>
        {% include 'game/partials/leaderboard_list.html' with leaderboards=leaderboards %}
        <small><i class="fa-solid fa-circle-info"></i>
            Access a different Leaderboard
        </small>
    </div>
    <hr class="title-line">
    <div class="col-lg-12 ">
        <h5><i class="fa-solid fa-dice"></i> Next 3 Games</h5>
        {% include 'game/partials/leaderboard_list.html' with leaderboards=next_games %}
        <small><i class="fa-solid fa-circle-info"></i>
            Access a future Game
        </small>
    </div>
    <hr class="title-line">
    <div class="col-lg-12 ">
        <h5><i class="fa-solid fa-dice"></i> Previous 3 Games</h5>
        {% include 'game/partials/leaderboard_list.html' with leaderboards=prev_games %}
        <small><i class="fa-solid fa-circle-info"></i>
            Access a finished Game
        </small>
    </div>
    <hr class="title-line">
</div>

footypicks/game/templates/game/partials/simple_form.html
{% load crispy_forms_tags %}
<form method="POST" id="simple-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-default btn-sm m-1" name="submit" type="submit">
    <a href="javascript:window.history.back()" class="btn btn-secondary btn-sm m-1" name="cancel">Cancel</a>
</form>

footypicks/game/templates/game/partials/top_menu.html
{% load static %}
<div class="container">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">The Footy Picks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'game:minileague_detail' pk=0 %}">Play <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'game:about' %}">About <span class="sr-only"></span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'game:player_detail' pk=request.user.player.id %}">Profile <span class="sr-only"></span></a>
            </li>
            {% endif %}
            {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
        </ul>
        {% endif %}
        {% if user.is_authenticated %}
        <ul class="navbar-nav mr-right">
            <li class="nav-item">
                <a class="nav-link">Logged in as {{ user.username }}</a>
            </li>
            <form class="form-inline my-2 my-lg-0" action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-default my-2 my-sm-0" type="submit">Logout</button>
            </form>
        </ul>
        {% else %}
        <ul class="navbar-nav mr-right">
            <li class="nav-item">
            <a href="{% url 'login' %}" class="btn btn-default my-2 my-sm-0 p-2">Login</a>
            </li>
        </ul>
        {% endif %}

    </div>
</nav>

</div>
<div id="grad-nav"></div>

footypicks/game/templates/game/partials/transaction_list.html
<table class="table table-sm small table-hover">
    <thead>
    <th>Type</th>
    <th>Date</th>
    <th>Amount</th>
    <th>Cleared</th>
    <th>Note</th>
    </thead>
    {% for tran in transactions %}
    <tr>
        <td>{{ tran.get_type_display }}</td>
        <td>{{ tran.date|date:"d/m/Y" }}</td>
        <td>
            {% if tran.type == "TT" or tran.type == "O" or tran.type == "F" %}
            <span style="color: #DA4453">-
            {% endif %}
            &pound;{{ tran.amount|floatformat:2  }}
            {% if tran.type == "TT" or tran.type == "O" or tran.type == "F" %}
            </span>
            {% endif %}
        </td>
        <td>
            {% if tran.pending %}
            ...Pending...
            {% else %}
            {{ tran.confirmed_date|date:"d/m/Y" }}
            {% endif %}
        </td>
        <td>{{ tran.note|default_if_none:"" }}</td>
    </tr>
    {% endfor %}
</table>